baseURL = "https://example.com"
languageCode = "en-us"
title = "Showery's Blog"
theme = "yinyang"
DefaultContentLanguage = "en"

[author]
  name = "Showery Hwang"
  homepage = "https://showery.netlify.com/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 3
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 2
  [languages.jp]
    contentDir = "content/jp"
    languageName = "Japanese"
    weight = 1

[params]
disqus = "showery" # disqus account name
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://showery.netlify.com/"
